# Plugin display language
pluginLanguage: en_US
# delete or not delete invalid @ in message
deleteInvalidAtInMessage: false
# display time (tick (1s=20t))
alertTitle:
  fadeIn: 10
  stay: 80
  fadeOut: 10
playerIgnore: { }
